-- ClickHouse DDL — GitHub AI Trend Analyzer
-- Executed automatically on first container start via docker-entrypoint-initdb.d/

-- Create database if not exists
CREATE DATABASE IF NOT EXISTS github_analyzer;

-- ── Table: github_data ───────────────────────────────────────────────────────
-- Single source of truth for events + repo metadata snapshot.
CREATE TABLE IF NOT EXISTS github_analyzer.github_data
(
    event_id     String,
    event_type   LowCardinality(String),
    actor_id     Int64,
    actor_login  String,
    repo_id      Int64,
    repo_name    String,
    created_at   DateTime('UTC'),
    payload_json String   DEFAULT '',
    repo_stargazers_count Int64 DEFAULT 0,
    repo_primary_language LowCardinality(String) DEFAULT '',
    repo_topics Array(String),
    repo_description String DEFAULT '',
    ingested_at  DateTime('UTC') DEFAULT now()
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(created_at)
ORDER BY (repo_id, created_at)
SETTINGS index_granularity = 8192;

-- ── Table: repo_metadata ─────────────────────────────────────────────────────
-- Latest synced GitHub repository metadata used by dashboard/API queries.
CREATE TABLE IF NOT EXISTS github_analyzer.repo_metadata
(
    repo_id Int64,
    repo_full_name String,
    repo_name String,
    node_id String,
    private UInt8,

    html_url String,
    clone_url String,
    homepage String,

    stargazers_count Int64,
    watchers_count Int64,
    forks_count Int64,
    open_issues_count Int64,
    network_count Int64,
    subscribers_count Int64,
    size_kb Int64,

    github_created_at DateTime('UTC'),
    github_updated_at DateTime('UTC'),
    github_pushed_at DateTime('UTC'),

    primary_language LowCardinality(String),
    topics Array(String),
    visibility LowCardinality(String),
    default_branch String,
    description String,
    category LowCardinality(String),

    is_fork UInt8,
    is_archived UInt8,
    is_disabled UInt8,
    has_issues UInt8,
    has_wiki UInt8,
    has_discussions UInt8,
    has_pages UInt8,
    allow_forking UInt8,
    is_template UInt8,

    owner_login String,
    owner_id Int64,
    owner_type LowCardinality(String),
    owner_avatar_url String,

    license_key String,
    license_name String,
    license_spdx_id String,

    rank Int32,
    fetched_at DateTime('UTC'),
    refreshed_at DateTime('UTC')
)
ENGINE = ReplacingMergeTree(refreshed_at)
PARTITION BY toYYYYMM(refreshed_at)
ORDER BY repo_full_name
SETTINGS index_granularity = 8192;

-- ── Table: repo_metadata_history ────────────────────────────────────────────
-- Append-only-ish audit log of repository metadata snapshots per fetch cycle.
-- Duplicate replays with the same repo/source/timestamp collapse on merge.
CREATE TABLE IF NOT EXISTS github_analyzer.repo_metadata_history
(
    repo_id Int64,
    repo_full_name String,
    repo_name String,
    node_id String,
    private UInt8,

    html_url String,
    clone_url String,
    homepage String,

    stargazers_count Int64,
    watchers_count Int64,
    forks_count Int64,
    open_issues_count Int64,
    network_count Int64,
    subscribers_count Int64,
    size_kb Int64,

    github_created_at DateTime('UTC'),
    github_updated_at DateTime('UTC'),
    github_pushed_at DateTime('UTC'),

    primary_language LowCardinality(String),
    topics Array(String),
    visibility LowCardinality(String),
    default_branch String,
    description String,
    category LowCardinality(String),

    is_fork UInt8,
    is_archived UInt8,
    is_disabled UInt8,
    has_issues UInt8,
    has_wiki UInt8,
    has_discussions UInt8,
    has_pages UInt8,
    allow_forking UInt8,
    is_template UInt8,

    owner_login String,
    owner_id Int64,
    owner_type LowCardinality(String),
    owner_avatar_url String,

    license_key String,
    license_name String,
    license_spdx_id String,

    rank Int32,
    fetched_at DateTime('UTC'),
    refreshed_at DateTime('UTC'),
    snapshot_at DateTime('UTC'),
    snapshot_source LowCardinality(String),
    snapshot_key String
)
ENGINE = ReplacingMergeTree(snapshot_at)
PARTITION BY toYYYYMM(snapshot_at)
ORDER BY (repo_full_name, snapshot_source, snapshot_at, snapshot_key)
SETTINGS index_granularity = 8192;

-- ── Table: repo_star_counts ──────────────────────────────────────────────────
-- Daily star deltas generated by the Spark batch aggregation job.
CREATE TABLE IF NOT EXISTS github_analyzer.repo_star_counts
(
    event_date Date,
    repo_name String,
    star_count Int64
)
ENGINE = SummingMergeTree()
PARTITION BY toYYYYMM(event_date)
ORDER BY (repo_name, event_date)
SETTINGS index_granularity = 8192;

-- ── Table: repo_activity_summary ─────────────────────────────────────────────
-- Weekly aggregate counts generated by the Spark batch aggregation job.
CREATE TABLE IF NOT EXISTS github_analyzer.repo_activity_summary
(
    repo_name String,
    event_type LowCardinality(String),
    event_count Int64,
    unique_actors Int64,
    first_seen_at DateTime('UTC'),
    last_seen_at DateTime('UTC'),
    computed_at DateTime('UTC')
)
ENGINE = ReplacingMergeTree(computed_at)
PARTITION BY toYYYYMM(computed_at)
ORDER BY (repo_name, event_type)
SETTINGS index_granularity = 8192;

-- ── Access: read-only viewer user ───────────────────────────────────────────
-- Intended for external access without any write or DDL privileges.
CREATE USER IF NOT EXISTS viewer IDENTIFIED WITH plaintext_password BY 'viewer';
GRANT SHOW, SELECT ON github_analyzer.* TO viewer;
