repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - clickhouse-driver>=0.2.9,<0.3.0
          - fastapi>=0.115.0,<0.116.0
          - httpx>=0.27.0,<0.28.0
          - opentelemetry-exporter-otlp>=1.27.0,<2.0.0
          - opentelemetry-instrumentation-fastapi>=0.48b0,<1.0.0
          - opentelemetry-sdk>=1.27.0,<2.0.0
          - pydantic>=2.8.0,<3.0.0
          - pydantic-settings>=2.3.0,<3.0.0
          - pyarrow>=17.0.0,<18.0.0
          - python-dotenv>=1.0.1,<2.0.0
          - structlog>=24.4.0,<25.0.0
  - repo: https://github.com/pytest-dev/pytest
    rev: 8.3.5
    hooks:
      - id: pytest
        additional_dependencies:
          - clickhouse-driver>=0.2.9,<0.3.0
          - fastapi>=0.115.0,<0.116.0
          - httpx>=0.27.0,<0.28.0
          - pydantic>=2.8.0,<3.0.0
          - pydantic-settings>=2.3.0,<3.0.0
          - pyarrow>=17.0.0,<18.0.0
          - pytest-asyncio>=0.24.0,<0.25.0
          - respx>=0.21.1,<0.22.0
          - structlog>=24.4.0,<25.0.0
        pass_filenames: false

