#!/usr/bin/env bash
# =============================================================================
# crontab_install.sh
#
# PURPOSE : Install all GitHub AI Trend Analyzer cron jobs.
#
# USAGE   :
#   ./scheduler/crontab_install.sh            # install cron jobs
#   ./scheduler/crontab_install.sh --uninstall # remove all GHA cron jobs
#
# EFFECTS :
#   - Appends GHA cron block to current user's crontab (idempotent).
#   - Creates scheduler/logs/ and scheduler/state/ directories.
#
# IDEMPOTENT: YES — running multiple times does not duplicate cron entries.
#             Each run removes the old GHA block first, then re-adds it.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SCRIPTS_DIR="${SCRIPT_DIR}/scripts"

UNINSTALL=0

for arg in "$@"; do
  case "${arg}" in
    --uninstall)    UNINSTALL=1 ;;
    --help|-h)
      echo "Usage: $0 [--uninstall]"
      exit 0 ;;
    *)
      echo "Unknown argument: ${arg}" >&2
      exit 1 ;;
  esac
done

# ── Prerequisite checks ───────────────────────────────────────────────────────
if [[ ! -f "${SCRIPTS_DIR}/00_env.sh" ]]; then
  echo "[ERROR] scheduler/scripts/00_env.sh not found. Run from project root." >&2
  exit 1
fi

# Make all scripts executable
chmod +x "${SCRIPTS_DIR}"/*.sh

# Create required directories
mkdir -p "${PROJECT_ROOT}/scheduler/logs"
mkdir -p "${PROJECT_ROOT}/scheduler/state"

echo "[INFO] Project root: ${PROJECT_ROOT}"
echo "[INFO] Scripts dir:  ${SCRIPTS_DIR}"

# ── Cron block markers ────────────────────────────────────────────────────────
CRON_BEGIN="# >>> GHA_SCHEDULER_BEGIN <<<"
CRON_END="# >>> GHA_SCHEDULER_END <<<"

# ── Uninstall mode ────────────────────────────────────────────────────────────
if [[ "${UNINSTALL}" -eq 1 ]]; then
  echo "[INFO] Removing GHA cron entries..."
  EXISTING_CRON=$(crontab -l 2>/dev/null || true)
  NEW_CRON=$(
    echo "${EXISTING_CRON}" \
    | awk "/${CRON_BEGIN}/{found=1} !found{print} /${CRON_END}/{found=0}"
  )
  echo "${NEW_CRON}" | crontab -
  echo "[OK]  GHA cron entries removed."

  exit 0
fi

# ── Build cron block ──────────────────────────────────────────────────────────
# All times are UTC. Cron runs as the current user.
# MAILTO="" suppresses email for successful runs; failures still produce output.

CRON_BLOCK=$(cat <<CRON
${CRON_BEGIN}
SHELL=/bin/bash
MAILTO=""
# GitHub AI Trend Analyzer — automated scheduler
# Generated by crontab_install.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Project: ${PROJECT_ROOT}

# 01 — Nightly Spark batch aggregation (Parquet → ClickHouse)
#      Run at 02:00 UTC, after midnight data is settled
0 2 * * * "${SCRIPTS_DIR}/01_nightly_batch_aggregation.sh" >> "${PROJECT_ROOT}/scheduler/logs/cron.log" 2>&1

# 02 — Kafka consumer lag check (every 5 min)
*/5 * * * * "${SCRIPTS_DIR}/02_kafka_lag_check.sh" >> "${PROJECT_ROOT}/scheduler/logs/cron.log" 2>&1

# 03 — ClickHouse data freshness check (every 5 min)
*/5 * * * * "${SCRIPTS_DIR}/03_data_freshness_check.sh" >> "${PROJECT_ROOT}/scheduler/logs/cron.log" 2>&1

# 04 — Parquet cleanup — delete partitions older than 90 days (Sunday 03:00 UTC)
0 3 * * 0 "${SCRIPTS_DIR}/04_parquet_cleanup.sh" >> "${PROJECT_ROOT}/scheduler/logs/cron.log" 2>&1

# 05 — ClickHouse OPTIMIZE FINAL on ReplacingMergeTree tables (Sunday 04:00 UTC)
0 4 * * 0 "${SCRIPTS_DIR}/05_clickhouse_optimize.sh" >> "${PROJECT_ROOT}/scheduler/logs/cron.log" 2>&1

# 06 — GitHub API token validation (daily 01:00 UTC — before batch starts)
0 1 * * * "${SCRIPTS_DIR}/06_token_validation.sh" >> "${PROJECT_ROOT}/scheduler/logs/cron.log" 2>&1

# 07 — Repo metadata refresh — re-fetch stars/forks/topics (daily 06:00 UTC)
0 6 * * * "${SCRIPTS_DIR}/07_repo_metadata_refresh.sh" >> "${PROJECT_ROOT}/scheduler/logs/cron.log" 2>&1

# 08 — Full pipeline health check (every 5 min)
*/5 * * * * "${SCRIPTS_DIR}/08_health_check.sh" >> "${PROJECT_ROOT}/scheduler/logs/cron.log" 2>&1

${CRON_END}
CRON
)

# ── Remove old GHA block + install new ───────────────────────────────────────
EXISTING_CRON=$(crontab -l 2>/dev/null || true)

# Strip old GHA block
CLEAN_CRON=$(
  echo "${EXISTING_CRON}" \
  | awk "/${CRON_BEGIN//\//\\/}/{found=1} !found{print} /${CRON_END//\//\\/}/{found=0}"
)

# Remove trailing blank lines from existing cron, then append new block
printf '%s\n\n%s\n' "${CLEAN_CRON}" "${CRON_BLOCK}" | crontab -

echo ""
echo "[OK]  Cron jobs installed. Current GHA crontab entries:"
echo "──────────────────────────────────────────────────────"
crontab -l | awk "/${CRON_BEGIN//\//\\/}/{found=1} found{print} /${CRON_END//\//\\/}/{found=0}"
echo "──────────────────────────────────────────────────────"

echo ""
echo "[OK]  GitHub AI Trend Analyzer scheduler installation complete."
echo ""
echo "Log files:    ${PROJECT_ROOT}/scheduler/logs/"
echo "State files:  ${PROJECT_ROOT}/scheduler/state/"
echo ""
echo "Verify health status: cat ${PROJECT_ROOT}/scheduler/state/health.json"
